### ISSUE TITLE
Error when running gatsby develop command

### ISSUE THREAD

**Issue by vagyvin** [mobelop/gatsby-source-magento2#17]
When I run `gatsby develop` command I get this error

TypeError: Cannot read property 'types' of undefined
    at buildTypeMap (node_modules/gatsby-source-magento2/nodes/utils/schema.js:497:22)
    at convertMagentoSchemaToGatsby (node_modules/gatsby-source-magento2/nodes/utils/schema.js:28:17)
    at _callee2$ (node_modules/gatsby-source-magento2/gatsby-node.js:104:81)
    at tryCatch (/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by eli9000** [comment]
I was getting the same error but resolved it... I was running a local instance of Magento in a Docker container.
My problem was that in the `gatsby-config.js` file I had set the `graphqlEndpoint` value as **https://localhost/graphql**
I removed the 's' from the URL and it worked fine.

Hope this helps
